### ISSUE TITLE
uni-app 原生插件 设置show_log为true 调试面板并未看到日志

### ISSUE THREAD

**Issue by Broly789** [sensorsdata/uni-app-native-plugin#1]
在manifest.json中show_log配置为了true，而且代码中也设置了为true 开启log, app真机调试面板中并未看到日志，平台了成功看到了数据
```js
// 神策埋点
this.$store.state.sensors.trackAppInstall()
this.$store.state.sensors.login(this.vuex_srId)
this.$store.state.sensors.setServerUrl(this.$store.state.server_url)
this.$store.state.sensors.enableLog(true) // 开启log
```

**Comment by cr1106** [comment]
请问下是使用的什么平台，iOS 还是 Android ，Android 需要在 adb logcat 中查看

**Comment by Broly789** [comment]
> 请问下是使用的什么平台，iOS 还是 Android ，Android 需要在 adb logcat 中查看

IOS

**Comment by cr1106** [comment]
> > 请问下是使用的什么平台，iOS 还是 Android ，Android 需要在 adb logcat 中查看
> 
> IOS

iOS 仅支持在 Xcode 中查看日志输出

**Comment by dev-dylan** [comment]
iOS 仅支持在 Xcode 中查看日志输出
