### ISSUE TITLE
arr源码包在哪里？

### ISSUE THREAD

**Issue by wd2010** [sensorsdata/uni-app-native-plugin#2]
你好，请问下可以自定义改造arr包吗？

**Comment by liuweiqiang2016** [comment]
是指这个 aar 吗？
https://github.com/sensorsdata/uni-app-native-plugin/blob/main/Sensorsdata-UniPlugin-App/android/SensorsdataUniPlugin.aar

**Comment by wd2010** [comment]
是的，我想基于我自己的业务逻辑进行改造，请问可以开源这个aar包的源码吗？

**Comment by liuweiqiang2016** [comment]
源码见这里：https://github.com/sensorsdata/uni-app-native-plugin/tree/main/android
